services:
  selenium:
    build: ./
    container_name: Emarge
    shm_size: 2g
    volumes:
      - ./app/:/app/
    env_file:
      - ./secrets.env
    environment:
      - FORMATION=
      - ANNEE=
      - TP=
      - BLACKLIST=Entrainement Le Robert, Activités HACK2G2, Activités GCC
    restart: unless-stopped
